- name: create instances
  hosts: local
  connection: local
  
  vars:
    subnet_id: "subnet-0bc41aa50c0fccefc"
    security_group: "sg-0b9fd6aabf64f5c40"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend

  tasks:
  - name: Launch EC2 Instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "t2.micro"
      image_id: "{{ami_id}}" 
      security_group: "{{security_group}}"  
      vpc_subnet_id: "{{subnet_id}}"  
    loop: "{{ instances }}"
    
    register: ec2.instances

  - name: Display instance information
    ansible.builtin.debug:
      msg: "Launched instance ID is {{ ec2.instances[0].id }} with public IP {{ ec2.instances[0].public_ip_address }}"