- name: gather gather_facts
  hosts: web
  gather_facts: yes
  become: yes
  tasks:
    - name: Display OS information
      ansible.builtin.debug:
        msg: "The operating system is {{ ansible_facts['os_family'] }} and version is {{ ansible_facts['distribution_version'] }}"

    - name: Install nginx if RedHat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install nginx if Ubuntu
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
