- name: install and remove packages
  hosts: web
  become: yes
  tasks:
   
    - name: Install and remove packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nginx", state: "present" }
        - { name: "httpd", state: "absent" }  
        - { name: "mysql", state: "present" }   


      notify: 
        - Start Nginx
  handlers:
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes  
